---
apiVersion: v1
kind: Secret
metadata:
  name: rhsummit-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/Summit23DevRHEL/rhsummit-gateway-gitops
